[In Development] TryAdd, Keyed, and TryAddKeyed Attributes
patrickklaeren/AutoRegisterInject pull request #10
Opened 2024-04-19 03:55 UTC by ChaseDRedmon

Add initial support for TryAdd, AddKeyed, and TryAddKeyed DI methods that are discussed in issues #5 and #6.

2024-04-19 03:56 UTC, ChaseDRedmon commented
@patrickklaeren and @ristogod, here is an in-progress draft of what I'm working on to support the two other issues

2024-04-19 03:58 UTC, ChaseDRedmon commented on src/AutoRegisterInject/Generator.cs
> +                        string.Empty);
In progress. Will add / support the constructor's new argument to define a key for Keyed methods and TryAddKeyed methods

2024-04-19 03:59 UTC, ChaseDRedmon commented on src/AutoRegisterInject/AutoRegisteredClass.cs
> +internal record AutoRegisteredClass(string ClassName, AutoRegistrationType RegistrationType, string[] Interfaces, string? Key);
Adding the attribute constructor's key to this DTO here

2024-04-19 13:19 UTC, ristogod commented
@ChaseDRedmon Thanks. Looks good.

2024-04-20 20:04 UTC, ChaseDRedmon commented
I'm going to open this PR as ready to review. 

I need to write the other unit test cases for testing the new TryRegister, TryRegisterKeyed, and RegisterKeyed methods under the Tests project, but I think we could start reviewing the PR initially @patrickklaeren

2024-04-20 20:09 UTC, ChaseDRedmon commented
Version bump would also need to be incremented to v1.4

2024-04-21 21:09 UTC, patrickklaeren requested changes

2024-04-21 21:09 UTC, patrickklaeren commented on src/AutoRegisterInject.Tests/GenerationTests.cs
> +    internal RegisterKeyedScopedAttribute(string ServiceKey, params System.Type[] onlyRegisterAs) { }
```suggestion
    internal RegisterKeyedScopedAttribute(string serviceKey, params System.Type[] onlyRegisterAs) { }
```

2024-04-21 21:09 UTC, patrickklaeren commented on src/AutoRegisterInject.Tests/GenerationTests.cs
> +    internal TryRegisterKeyedScopedAttribute(string ServiceKey, params System.Type[] onlyRegisterAs) { }
```suggestion
    internal TryRegisterKeyedScopedAttribute(string serviceKey, params System.Type[] onlyRegisterAs) { }
```

2024-04-21 21:09 UTC, patrickklaeren commented on src/AutoRegisterInject.Tests/GenerationTests.cs
> +    internal RegisterKeyedSingletonAttribute(string ServiceKey, params System.Type[] onlyRegisterAs) { }
```suggestion
    internal RegisterKeyedSingletonAttribute(string serviceKey, params System.Type[] onlyRegisterAs) { }
```

2024-04-21 21:09 UTC, patrickklaeren commented on src/AutoRegisterInject.Tests/GenerationTests.cs
> +    internal TryRegisterKeyedSingletonAttribute(string ServiceKey, params System.Type[] onlyRegisterAs) { }
```suggestion
    internal TryRegisterKeyedSingletonAttribute(string serviceKey, params System.Type[] onlyRegisterAs) { }
```

2024-04-21 21:09 UTC, patrickklaeren commented on src/AutoRegisterInject.Tests/GenerationTests.cs
> +    internal RegisterKeyedTransientAttribute(string ServiceKey, params System.Type[] onlyRegisterAs) { }
```suggestion
    internal RegisterKeyedTransientAttribute(string serviceKey, params System.Type[] onlyRegisterAs) { }
```

2024-04-21 21:09 UTC, patrickklaeren commented on src/AutoRegisterInject.Tests/GenerationTests.cs
> +    internal TryRegisterKeyedTransientAttribute(string ServiceKey, params System.Type[] onlyRegisterAs) { }
```suggestion
    internal TryRegisterKeyedTransientAttribute(string serviceKey, params System.Type[] onlyRegisterAs) { }
```

2024-04-21 21:10 UTC, patrickklaeren commented
Minor change for the parameter name in constructor.

Will just need summary of attributes being added. Readme and Wiki needs to updated once released, I will add that as a chore for me to do.

2024-04-22 17:46 UTC, ChaseDRedmon commented
Summary:

Added 3 new attributes types

1. TryRegister
2. TryRegisterKeyed
3. RegisterKeyed

TryRegisterKeyed and RegisterKeyed methods take a ServiceKey argument where you must pass in a string type key. Failing to pass in a key, or setting an empty or whitespace key results in an argument exception that prevents the source generator from executing.

TryRegisterScoped, Singleton, and Transient attributes generate their corresponding extension methods: `ServiceCollection.TryRegisterScoped, ServiceCollection.TryRegisterSingleton, and ServiceCollection.TryRegisterTransient`

`Try`RegisterKeyedScoped, KeyedSingleton, and KeyedTransient attributes generate their corresponding extension methods: `ServiceCollection.TryRegisterKeyedScoped("Key"), ServiceCollection.TryRegisterKeyedSingleton("Key"), and ServiceCollection.TryRegisterKeyedTransient("Key")`

RegisterKeyedScoped, KeyedSingleton, and KeyedTransient attributes generate their corresponding extension methods: `ServiceCollection.RegisterKeyedScoped("Key"), ServiceCollection.RegisterKeyedSingleton("Key"), and ServiceCollection.RegisterKeyedTransient("Key")`

2024-04-22 19:18 UTC, merged